### PR TITLE
Update websocket library.

### PR DESCRIPTION
**Pull request by pavoni**
The library we were using was very old - and was stale for a long time.

But the great news is that https://github.com/websocket-client/websocket-client is now active - and has several years worth of bugfixes!

I'm hopeful it will close https://github.com/pavoni/pyroon/issues/54

This will require some testing!

### CODE REVIEW

**Comment by pavoni** [comment]
@doctorfree Do you have a view on this?

I'm tempted to merge and release a version using the new library - since it makes it easier to test in HA.

But don't want to mess up you or users of https://github.com/doctorfree/RoonCommandLine

**Comment by doctorfree** [comment]
I don't have a very good understanding of the changes involved in moving to the newer WebSocket client for Python. My initial impression is this would not impact RoonCommandLine. Regardless, my view is to improve the Python Roon API library and I will adjust accordingly as necessary.

**Comment by pavoni** [comment]
Thanks - I guess it’s mostly just a pretty big version change - so perhaps risky. 

I’ll do some more testing, it did work out the box though.

Once it looks good - I’ll build a library - and ask you to check it out.

**Comment by pavoni** [comment]
This is already looking good. It recovers reliably to a local roon core on my dev machine - which I can't get the old library to do.

**Pull request merged**
