### PR TITLE
CONTROL_VOLUME Code

### PR DESCRIPTION
**Pull request by JSonnabend**
Here's the code I worked up to control EventGhost from Roon volume change messages. I'm afraid it's not very "Python-esque" in style, but at least it's working for me. 

I'm happy to discuss details any time.

### CODE REVIEW

**Comment by pavoni** [comment]
Thanks very much for this.

The norm for PRs is that contributors go through a review  process to getting their code to the stage that it can be merged into the library. If you're interested I'm very happy to help you do this.

But if you don't want the hassle - I'm happy to take this on myself.

Let me know your thoughts.

**Comment by JSonnabend** [comment]
Greg -

I have some free time. If you don't mind a little mentoring, I'm happy to
learn.

**Comment by pavoni** [comment]
Thanks for being willing to do this. I think the sequence should be something like this:-

1. Get your environment working properly - so you can remove the various patches you needed to make to get things to run
2. Your `roon_api` changes were based on an old version of the library - so your new changes also include a number of changes that undo needed changes to the library - so we need to get rid of the incorrect changes
3. Slightly refactor the demo code to match the other demo examples
4. Tidy the code so it passed the lint checks etc 

So for 1 - the issue is that this is library designed to be installed via python's 'pip' mechanism. However when working in the library you can't use this easily. 

The environment should be setup via the `poetry` utility and the virtual environment.

You can see more about poetry here: https://python-poetry.org/docs/

But useful commands are:-
`poetry install` to get everything set up
`poetry run examples/demo.py` to run demo in the poetry environment
`poetry build` to run all the build & lint scripts

It might be easiest to start with a clean branch of the library  - perhaps in a new directory.

Then once you have poetry working - you should be able to copy across the needed changes from your old directory.

**Comment by pavoni** [comment]
The automatic build for your branch was reporting reformat errors in code you didn't touch.

Turned out this was because I'd not version controlled one of the tools correctly.

I've now fixed this in the master branch.

If you start a new branch - suggest you get your forked master branch back up to date 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by JSonnabend** [comment]
Whew, that's a lot. I'll tackle it in the coming days.

- Jeff

The Route 66 Primer <http://TheRoute66Primer.com> / Interstate Magazine
<http://www.interstatemagazine.com/>

718-440-1939 <http://voice.google.com/calls?a=nc,%2B17184401939>
<http://voice.google.com/calls?a=nc,%2B17184401939>

**Comment by pavoni** [comment]
It is quite a list.

I’m still very happy to take this on if it’s too much.

You didn’t come here wanting an open source bootcamp!

**Comment by JSonnabend** [comment]
I'll take a look at the various tutorials. One quick, basic question: when
I do a correct check-out/sync, does the folder structure on my machine
mirror the structure in the repository?

- Jeff

The Route 66 Primer <http://TheRoute66Primer.com> / Interstate Magazine
<http://www.interstatemagazine.com/>

718-440-1939 <http://voice.google.com/calls?a=nc,%2B17184401939>
<http://voice.google.com/calls?a=nc,%2B17184401939>

**Comment by pavoni** [comment]
Yes, a git checkout should replicate the repo structure locally.

Use a fresh directory if needed to avoid your old and new structure clashing.

**Comment by JSonnabend** [comment]
Greg -

I don't think I have the energy for this. I'm happy hacking away at code,
but the whole open source framework thing just makes my eyes glaze over.

What can I do to help with the code? I'm not sure I did all that much on my
end to the code you had given me, but I don't recall specificly.

- Jeff

The Route 66 Primer <http://TheRoute66Primer.com> / Interstate Magazine
<http://www.interstatemagazine.com/>

718-440-1939 <http://voice.google.com/calls?a=nc,%2B17184401939>
<http://voice.google.com/calls?a=nc,%2B17184401939>

**Comment by pavoni** [comment]
Completely understand.

I’ll pick this up, will come back to you if I need help, and to test.

**Comment by JSonnabend** [comment]
I've received a few automated emails saying the code isn't compiling. I
know my code was structured like shit, as Python is really new to me, as is
using GitHub.

The code has been tweaked in the repository, and there is a new project I'm
also working on at https://github.com/JSonnabend/roonServiceManager that
might be useful. I think my roonapi fork (
https://github.com/JSonnabend/pyroon) might also be different (or new)
since we last spoke.

All that to say, let me know if I can chip in and help with any of this.

- Jeff

The Route 66 Primer <http://TheRoute66Primer.com> / Interstate Magazine
<http://www.interstatemagazine.com/>

718-440-1939 <http://voice.google.com/calls?a=nc,%2B17184401939>
<http://voice.google.com/calls?a=nc,%2B17184401939>

**Comment by pavoni** [comment]
I've made a start - created a clean branch of my own - and worked through your code undoing incorrect changes / regressions in the core library functions - and leaving the handful of changes just putting back the volume endpoint code.

So next step if for me to understand your example code (and make sure I didn't break anything!).

**Comment by pavoni** [comment]
I need a little help. I think I have the code added. But I can't really understand what it's supposed to do.

Can you explain a bit about when the `volume_control_callback`  is called?

**Comment by JSonnabend** [comment]
It works like this. The extension registers as a volume control endpoint
with the core. After it's registered, that volume control shows up in the
device setup screen under volume type (or whatever the pull-down menu is,
my internet's down so I can't actually see it right now to confirm).

When a user selects the extension as the volume control, from that point
forward, whenever the user changes the volume at that endpoint, the core
sends a notice to the callback in the extension, and it's up to the
extension then to take whatever action is necessary to change the volume.

In my case, the extension runs on the host it is controlling, so I don't
have to worry about finding which endpoint sent the volume change request.
The extension is always going to change the volume on the host it's running
on. That is also why I named the volume control extension with the name of
the host, so that if it runs a multiple hosts, I can pick the right one.

Makes sense?

**Comment by pavoni** [comment]
Super helpful - thanks.

Now have it basically working - take a look at https://github.com/pavoni/pyroon/pull/70

Will close this for now - and we can continue the discussion in the other PR.

**Comment by pavoni** [comment]
@JSonnabend - I think https://github.com/pavoni/pyroon/pull/70 is now ready to merge.

Let me know if you have any comments.

Thanks for your help.

**Comment by JSonnabend** [comment]
Comments, like, "rock on" or something? ;-) Nope, all good. I'm psyched you
dug into this.

**Pull request closed without merging**
